<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Email;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\FunctionController;

class Gonggao extends Model{

    protected $table='cym_xiaoxi';

    public $timestamps=true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }
}